services:
  - type: web
    name: tele-member-api
    env: node
    plan: free
    buildCommand: pnpm install --frozen-lockfile && pnpm --filter @tele-member/api build
    startCommand: pnpm --filter @tele-member/api dev
    envVars:
      - key: NODE_ENV
        value: production
